[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
py-modules = []

[project]
name = "progressbar"
dynamic = ["version"]
description = "Progressbar"

dependencies = []
