[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
py-modules = []

[project]
name = "metrics-framework"
dynamic = ["version"]
description = "Metrics framework"

dependencies = ["numpy", "torch"]
